[package]
name = "anodyne-advance"
version = "0.1.0"
authors = ["lif <lifning+git@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba = { path = "../gba" }
